### ISSUE TITLE
Forge Crash 1.12.2

### ISSUE THREAD

**Issue by nico-bagel** [PersonTheCat/ore_stone_variants#103]
`Forge 14.23.5.2854`
`Minecraft 1.12.2`
`Ore Stone Variants v5.7`
A crash happened when I started up minecraft with this mod and Modern Metals. I tried deleting metals with no ores (alloys) from the OSV hjson configs but they came back every time I restarted the game and caused the error. Removing modernmetals_nichrome partially solved a problem, but instead stainlesssteel or galvanizedsteel was the culprit.

My idea of a solution is to make the feature of making ores from ore dictionaries alone to be toggled, so it can be turned off, or use a blacklist so that specific metal types can be blacklisted from attempting to be used in OSV to create ores. Please correct me if I'm wrong on any of my current understanding of the mod.

Here is a crash report below:

Time: 11/16/20 10:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (osv)
Caused by: java.lang.RuntimeException: There is no block named "modernmetals:stainlesssteel_ore."
	at com.personthecat.orestonevariants.util.CommonMethods.runExF(CommonMethods.java:83)
	at com.personthecat.orestonevariants.util.HjsonTools.noBlockNamed(HjsonTools.java:629)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$null$0(OreProperties.java:88)
	at com.personthecat.orestonevariants.properties.OreProperties$$Lambda$24623/593358868.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$new$1(OreProperties.java:88)
	at com.personthecat.orestonevariants.properties.OreProperties$$Lambda$23292/133462654.get(Unknown Source)
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35)
	at com.personthecat.orestonevariants.properties.RecipeProperties.create(RecipeProperties.java:68)
	at com.personthecat.orestonevariants.properties.RecipeProperties$$Lambda$24990/393082134.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.personthecat.orestonevariants.properties.RecipeProperties.setupRecipes(RecipeProperties.java:60)
	at com.personthecat.orestonevariants.recipes.RecipeHelper.registerRecipes(RecipeHelper.java:48)
	at com.personthecat.orestonevariants.recipes.RecipeHelper.handleRecipes(RecipeHelper.java:39)
	at com.personthecat.orestonevariants.Main.init(Main.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by nico-bagel** [comment]
Duplicate of #92 
Fixed with the solution there, issue closed.
