### ISSUE TITLE
Crash during Startup/Pre-initialization

### ISSUE THREAD

**Issue by Scrayyg** [PersonTheCat/ore_stone_variants#25]
Minecraft 1.12.2
Forge: 1.12.2 - 14.23.4.2729
Mods: 
Ice and Fire Dragons - 1.5.1
LLibrary 1.7.14
Ore Stone Variants 3.0

I was updating my mods when this crash happened. I managed to puzzle out the cause being OSV and IceandFire. This crash actually happens with OSV 2.23 as well. I honestly don't know what could be the problem cause it worked before I updated to 3.0 but after the crash I tried to run it with 2.23 but then that was crashing too.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/6/18 11:06 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (ore_stone_variants)
Caused by: java.lang.NullPointerException: name
	at java.util.zip.ZipFile.getEntry(Unknown Source)
	at personthecat.mod.util.ZipTools.isFileInZip(ZipTools.java:65)
	at personthecat.mod.util.ZipTools.getImageFromZip(ZipTools.java:81)
	at personthecat.mod.util.overlay.SpriteHandler.getImageFromFile(SpriteHandler.java:186)
	at personthecat.mod.util.overlay.SpriteHandler.createNormalOverlays(SpriteHandler.java:98)
	at personthecat.mod.util.overlay.SpriteHandler.testForAndCreateOverlay(SpriteHandler.java:77)
	at personthecat.mod.util.overlay.SpriteHandler.testForAndCreateOverlay(SpriteHandler.java:55)
	at personthecat.mod.util.overlay.SpriteHandler.createAllOverlays(SpriteHandler.java:35)
	at personthecat.mod.objects.model.ModelEventHandler.createAndAddSprites(ModelEventHandler.java:61)
	at personthecat.mod.objects.model.ModelEventHandler.createAndRegisterResourcePack(ModelEventHandler.java:49)
	at personthecat.mod.proxy.ClientProxy.createAndRegisterResourcePack(ClientProxy.java:18)
	at personthecat.mod.Main.preInit(Main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 302642056 bytes (288 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2729 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                        | Signature                                |
	|:----- |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.4.2729 | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | llibrary           | 1.7.14       | llibrary-1.7.14-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | iceandfire         | 1.5.1        | iceandfire-1.5.1-1.12.2.jar   | None                                     |
	| UCEE  | ore_stone_variants | 2.23         | ore_stone_variants-2.23.jar   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 650/PCIe/SSE2'

[crash-2018-07-06_10.55.39-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2170934/crash-2018-07-06_10.55.39-client.txt)

**Comment by Scrayyg** [comment]
I realize that I pasted the 2.23 crashlog but I linked the 3.0.
Here's the 3.0 Log and the .txt of the 2.23

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/6/18 10:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (ore_stone_variants)
Caused by: java.lang.NullPointerException: name
	at java.util.zip.ZipFile.getEntry(Unknown Source)
	at personthecat.mod.util.ZipTools.isFileInZip(ZipTools.java:65)
	at personthecat.mod.util.ZipTools.getImageFromZip(ZipTools.java:81)
	at personthecat.mod.util.overlay.SpriteHandler.getImageFromFile(SpriteHandler.java:186)
	at personthecat.mod.util.overlay.SpriteHandler.createNormalOverlays(SpriteHandler.java:98)
	at personthecat.mod.util.overlay.SpriteHandler.testForAndCreateOverlay(SpriteHandler.java:77)
	at personthecat.mod.util.overlay.SpriteHandler.testForAndCreateOverlay(SpriteHandler.java:55)
	at personthecat.mod.util.overlay.SpriteHandler.createAllOverlays(SpriteHandler.java:35)
	at personthecat.mod.objects.model.ModelEventHandler.createAndAddSprites(ModelEventHandler.java:61)
	at personthecat.mod.objects.model.ModelEventHandler.createAndRegisterResourcePack(ModelEventHandler.java:49)
	at personthecat.mod.proxy.ClientProxy.createAndRegisterResourcePack(ClientProxy.java:18)
	at personthecat.mod.Main.preInit(Main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 277761520 bytes (264 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2729 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                        | Signature                                |
	|:----- |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.4.2729 | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | llibrary           | 1.7.14       | llibrary-1.7.14-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | iceandfire         | 1.5.1        | iceandfire-1.5.1-1.12.2.jar   | None                                     |
	| UCEE  | ore_stone_variants | 3.0          | ore_stone_variants-3.0.jar    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 650/PCIe/SSE2'

[crash-2018-07-06_11.06.07-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2170980/crash-2018-07-06_11.06.07-client.txt)

**Comment by PersonTheCat** [comment]
Thanks for pointing this out! Unfortunately, I wasn't able to reproduce it using the same mod combination, as well as the same OS and Java version. It could be the slightly newer version of Forge that I haven't tested, but I think I can see what's going on in this crash, anyway. The mod is testing to see whether the texture already exists in the resource pack. If it doesn't, it definitely isn't supposed to crash. This exception is supposed to get caught and ignored. Please try the test build below. If that doesn't fix the issue, I'll try again to reproduce it, but I may wind up needing to send you a diagnostic build to help me out. Thanks! 

[ore_stone_variants-3.0.1.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2171145/ore_stone_variants-3.0.1.zip)

**Comment by Scrayyg** [comment]
Hmm, it still crashed even with the test build. I gave it a shot on a fresh install of minecraft as well, but it still crashed. I also gave it a shot on the recommended Forge 2705 instead of the latest and it still crashed. I attached the logs of the different attempts with different setups I don't know if that will help or not.


[Fresh Install OSV 3.0.1 Forge 2705.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171299/Fresh.Install.OSV.3.0.1.Forge.2705.txt)
[Fresh Install OSV 3.0.1 Forge 2729.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171300/Fresh.Install.OSV.3.0.1.Forge.2729.txt)
[OSV 3.0 Forge 2705.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171301/OSV.3.0.Forge.2705.txt)
[OSV 3.0 Forge 2729.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171302/OSV.3.0.Forge.2729.txt)
[OSV 3.0.1 Forge 2705 .txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171303/OSV.3.0.1.Forge.2705.txt)
[OSV 3.0.1 Forge 2729.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171304/OSV.3.0.1.Forge.2729.txt)
[Fresh Install OSV 3.0 Forge 2705.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171305/Fresh.Install.OSV.3.0.Forge.2705.txt)
[Fresh Install OSV 3.0 Forge 2729.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2171306/Fresh.Install.OSV.3.0.Forge.2729.txt)

**Comment by PersonTheCat** [comment]
I'm not sure why this didn't happen to me previously. It seems I forgot something somewhere and maybe there was just a difference in the development build I was using. Regardless, there was a typo in the texture's name. That should definitely mess things up. Thanks for the help and patience while I realized my mistake. If you like, you can help me test it again before the next patch. Just let me know if it does or doesn't crash for you. Thanks again!

[ore_stone_variants-3.0.4.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2172315/ore_stone_variants-3.0.4.zip)

**Comment by Scrayyg** [comment]
Glad to help. Tried out the new one and it works fine. Thanks again.

**Comment by PersonTheCat** [comment]
As this fix has already been verified, I will be closing this issue.
