### ISSUE TITLE
[Crash] Server crash using the latest release

### ISSUE THREAD

**Issue by T145** [PersonTheCat/ore_stone_variants#39]
```java
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/BlockStateMapper
    at personthecat.mod.util.CommonMethods.getModelResourceLocation(CommonMethods.java:43)
    at personthecat.mod.objects.blocks.BlockOresBase.setBackgroundModels(BlockOresBase.java:131)
    at personthecat.mod.objects.blocks.BlockOresBase.<init>(BlockOresBase.java:101)
    at personthecat.mod.objects.blocks.BlockOresBase.<init>(BlockOresBase.java:113)
    at personthecat.mod.init.BlockInit.initOres(BlockInit.java:57)
    at personthecat.mod.init.BlockInit.init(BlockInit.java:38)
    at personthecat.mod.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_150_RegistryHandler_onBlockRegister_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.statemap.BlockStateMapper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
Caused by: java.lang.NullPointerException
```
## Mod List
```
 FML: MCP 9.42 Powered by Forge 14.23.4.2759 173 mods loaded, 173 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                   | Version                  | Source                                        | Signature                                |
       |:----- |:------------------------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft                            | 1.12.2                   | minecraft.jar                                 | None                                     |
       | UCH   | mcp                                  | 9.42                     | minecraft.jar                                 | None                                     |
       | UCH   | FML                                  | 8.0.99.99                | forge-1.12.2-14.23.4.2759-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                                | 14.23.4.2759             | forge-1.12.2-14.23.4.2759-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | infinimend                           | 1.0.2                    | minecraft.jar                                 | None                                     |
       | UCH   | OpenEye                              | 0.8                      | OpenEye-1.12.2-0.8.jar                        | None                                     |
       | UCH   | smoothfontcore                       | 1.12.2-1.16              | minecraft.jar                                 | None                                     |
       | UCH   | openmodscore                         | 0.12                     | minecraft.jar                                 | None                                     |
       | UCH   | bowinfinityfix                       | rv5                      | minecraft.jar                                 | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
       | UCH   | foamfixcore                          | 7.7.4                    | minecraft.jar                                 | None                                     |
       | UCH   | passableleavescore                   | 1.0.0                    | minecraft.jar                                 | None                                     |
       | UCH   | randompatches                        | 1.12.2-1.5.0.4           | randompatches-1.12.2-1.5.0.4.jar              | None                                     |
       | UCH   | aiimprovements                       | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
       | UCH   | akashictome                          | 1.2-10                   | AkashicTome-1.2-10.jar                        | None                                     |
       | UCH   | craftstudioapi                       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
       | UCH   | harvestcraft                         | 1.12.2z                  | Pam's+HarvestCraft+1.12.2z.jar                | None                                     |
       | UCH   | quark                                | r1.5-130                 | Quark-r1.5-130.jar                            | None                                     |
       | UCH   | animania                             | 1.5.1.1                  | animania-1.12.2-1.5.1.1.jar                   | None                                     |
       | UCH   | applecore                            | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                  | None                                     |
       | UCH   | toughasnails                         | 3.1.0.115                | ToughAsNails-1.12.2-3.1.0.115-universal.jar   | None                                     |
       | UCH   | applejuiceskin                       | 1.0.0.4                  | applejuiceskin-1.12.2-1.0.0.4.jar             | None                                     |
       | UCH   | crafttweaker                         | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
       | UCH   | mtlib                                | 3.0.5                    | MTLib-3.0.5.jar                               | None                                     |
       | UCH   | modtweaker                           | 4.0.13                   | modtweaker-4.0.14.jar                         | None                                     |
       | UCH   | jei                                  | 4.12.0.216               | jei_1.12.2-4.12.0.216.jar                     | None                                     |
       | UCH   | appleskin                            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
       | UCH   | aqua_creepers                        | 1.2.3                    | AquaCreepers-1.2.3.jar                        | None                                     |
       | UCH   | aroma1997core                        | 2.0.0.0                  | Aroma1997Core-1.12.2-2.0.0.0.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCH   | aromabackup                          | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCH   | aromabackuprecovery                  | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCH   | attributefix                         | 1.0.1                    | AttributeFix-1.12.2-1.0.1.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | morphtool                            | 1.2-16                   | Morph-o-Tool-1.2-16.jar                       | None                                     |
       | UCH   | autoreglib                           | 1.3-20                   | AutoRegLib-1.3-20.jar                         | None                                     |
       | UCH   | badwithernocookiereloaded            | 1.12.2-3.1.14            | badwithernocookiereloaded-1.12.2-3.1.14.jar   | None                                     |
       | UCH   | baubles                              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
       | UCH   | bedpatch                             | 2.2                      | bedpatch-2.2-1.12.2.jar                       | 6bf7527e690fb5e8719b9832bce5000a3e87dfe6 |
       | UCH   | bedrockreplacer                      | 7.0.2                    | BedrockReplacer-Forge-7.0.2.jar               | None                                     |
       | UCH   | betteradvancements                   | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar        | None                                     |
       | UCH   | betterthanmending                    | 1.1.1                    | BetterThanMending-1.1.1.jar                   | None                                     |
       | UCH   | bibliocraft                          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
       | UCH   | bloodmoon                            | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCH   | bookshelf                            | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | bullseye                             | 3.0.6                    | Bullseye-1.12.2-3.0.6.jar                     | None                                     |
       | UCH   | caliper                              | 1.1.34                   | Caliper-1.12.2-1.1.34.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | canijoinnow                          | @VERSION@                | CanIJoinNow-1.12.1-1.1-3.jar                  | None                                     |
       | UCH   | chameleoncreepers                    | 1.4.1                    | chameleoncreepers-1.4.1-1.12.jar              | None                                     |
       | UCH   | chunkpregenerator                    | 1.8                      | Chunk+Pregenerator+V1.12-1.8.2.jar            | None                                     |
       | UCH   | clumps                               | 3.1.1                    | Clumps-3.1.1.jar                              | None                                     |
       | UCH   | codechickenlib                       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | compot                               | 1.1                      | CombinedPotions-1.12-1.1.jar                  | None                                     |
       | UCH   | morpheus                             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                       | None                                     |
       | UCH   | comforts                             | 1.3.0                    | comforts-1.12.2-1.3.0.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCH   | cyclopscore                          | 0.11.10                  | CyclopsCore-1.12.2-0.11.10.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCH   | commoncapabilities                   | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar             | None                                     |
       | UCH   | containerfix                         | 1.0                      | ContainerFix+MC1.12.2+v1.0.jar                | None                                     |
       | UCH   | cookingforblockheads                 | 6.4.65                   | CookingForBlockheads_1.12.2-6.4.65.jar        | None                                     |
       | UCH   | extendedrenderer                     | v1.0                     | coroutil-1.12.1-1.2.13.jar                    | None                                     |
       | UCH   | coroutil                             | 1.12.1-1.2.13            | coroutil-1.12.1-1.2.13.jar                    | None                                     |
       | UCH   | configmod                            | v1.0                     | coroutil-1.12.1-1.2.13.jar                    | None                                     |
       | UCH   | cosmeticarmorreworked                | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCH   | corpsecomplex                        | 1.0.2.2                  | corpsecomplex-1.12.2-1.0.2.2.jar              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCH   | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCH   | craftingtweaks                       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar               | None                                     |
       | UCH   | crafttweakerjei                      | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
       | UCH   | deathquotes                          | 1.2.0                    | DeathQuotes-1.2.0-mc1.12-forge.jar            | None                                     |
       | UCH   | diethopper                           | 1.1                      | diethopper-1.1.jar                            | None                                     |
       | UCH   | dirt2path                            | 1.7.1                    | dirt2path-1.8.0.jar                           | None                                     |
       | UCH   | doggytalents                         | 1.14.2.321               | Doggy+Talents-1.12.2-1.14.2.321-universal.jar | None                                     |
       | UCH   | dsurround                            | 3.4.9.16                 | DynamicSurroundings-1.12.2-3.4.9.16.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UCH   | eplus                                | 5.0.169                  | EnchantingPlus-1.12.2-5.0.169.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | endercompass                         | 1.2.6.2                  | EnderCompass-1.12-1.2.6.2.jar                 | None                                     |
       | UCH   | enderstorage                         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | enderzoo                             | 1.12.1-1.4.0.49          | EnderZoo-1.12.1-1.4.0.49.jar                  | None                                     |
       | UCH   | epicsiegemod                         | 13.163                   | EpicSiegeMod-13.163.jar                       | None                                     |
       | UCH   | shadowmc                             | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                       | None                                     |
       | UCH   | extrarails                           | 1.3.0                    | ExtraRails-1.12-1.3.0.jar                     | None                                     |
       | UCH   | fairylights                          | 2.1.4                    | fairylights-2.1.4-1.12.2.jar                  | None                                     |
       | UCH   | fasterladderclimbing                 | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar         | None                                     |
       | UCH   | fastfurnace                          | 1.1.0                    | FastFurnace-1.12.2-1.1.0.jar                  | None                                     |
       | UCH   | fastbench                            | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                | None                                     |
       | UCH   | fencejumper                          | 1.0.5                    | fencejumper-1.12-1.0.5.jar                    | None                                     |
       | UCH   | ferdinandsflowers                    | 1.10.1b                  | Ferdinand's+Flowers-1.10.1b-1.12.jar          | None                                     |
       | UCH   | foamfix                              | 0.10.1-1.12.2            | foamfix-0.10.1-1.12.2.jar                     | None                                     |
       | UCH   | forgelin                             | 1.7.4                    | Forgelin-1.7.4.jar                            | None                                     |
       | UCH   | friendlyfire                         | 1.5.8                    | FriendlyFire-1.12.2-1.5.8.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | gravelminer                          | 6.1.2                    | GravelMiner_1.12.1-6.1.2.jar                  | None                                     |
       | UCH   | headcrumbs                           | 2.0.4                    | Headcrumbs-1.12.2-2.0.4.15.jar                | None                                     |
       | UCH   | helpfixer                            | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                   | None                                     |
       | UCH   | holoinventory                        | 2.1.1.151                | HoloInventory-1.12.2-2.1.1.151.jar            | None                                     |
       | UCH   | horsetweaks                          | 1.0.4                    | HorseTweaks_1.12.2-1.0.4.jar                  | None                                     |
       | UCH   | hungerinpeace                        | 1.0.0                    | HungerInPeace-mc1.12-1.0.0.jar                | None                                     |
       | UCH   | waila                                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | UCH   | ichunutil                            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
       | UCH   | infernalmobs                         | 1.7.5                    | InfernalMobs-1.12.2.jar                       | None                                     |
       | UCH   | initialinventory                     | 2.0.2                    | InitialInventory-3.0.0.jar                    | None                                     |
       | UCH   | mantle                               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
       | UCH   | inspirations                         | 1.12.2-0.2.1             | Inspirations-1.12.2-0.2.1.jar                 | None                                     |
       | UCH   | inventorysorter                      | 1.13.3+57                | inventorysorter-1.12.2-1.13.3+57.jar          | None                                     |
       | UCH   | inventorytweaks                      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCH   | jepb                                 | 1.2.1                    | jepb-1.12-1.2.1.jar                           | None                                     |
       | UCH   | jaff                                 | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
       | UCH   | jeid                                 | 1.0.1-16                 | JustEnoughIDs-1.0.1-16.jar                    | None                                     |
       | UCH   | kleeslabs                            | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                   | None                                     |
       | UCH   | laggoggles                           | FORGE-1.12.2-4.1         | LagGoggles-FORGE-1.12.2-4.1.jar               | None                                     |
       | UCH   | lunatriuscore                        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
       | UCH   | laserlevel                           | 2.1.0.19                 | LaserLevel-1.12.2-2.1.0.19-universal.jar      | None                                     |
       | UCH   | lessforgivingvoid                    | 1.0.1                    | LessForgivingVoid-1.0.1.jar                   | None                                     |
       | UCH   | loadingprofiler                      | 1.1                      | LoadingProfiler-MC1.12-1.3.jar                | None                                     |
       | UCH   | login_shield                         | 1.12.2-3-g7c6e7ac        | Login_Shield-1.12.2-3-g7c6e7ac.jar            | None                                     |
       | UCH   | mendingfix                           | 1.0.1-1.12.2.2618        | mendingfix-1.0.1-1.12.2.2618.jar              | None                                     |
       | UCH   | mobamputation                        | 7.0.0                    | MobAmputation-1.12.2-7.0.0.jar                | None                                     |
       | UCH   | modlister                            | 1.12.2-3.2.4             | ModLister-1.12.2-3.2.4.jar                    | None                                     |
       | UCH   | concheckrmd                          | 1.6                      | Modpack+Configuration+Checker-1.12.2-v1.6.jar | None                                     |
       | UCH   | naturalnetherportals                 | 1.2.0                    | naturalnetherportals-1.2.0-mc1.12.x.jar       | None                                     |
       | UCH   | naturescompass                       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
       | UCH   | netherchest                          | 0.2.3                    | netherchest-0.2.3.jar                         | None                                     |
       | UCH   | netherportalfix                      | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar             | None                                     |
       | UCH   | nofov                                | 1.0.1                    | NoFov-MC1.12-1.0.1.jar                        | None                                     |
       | UCH   | nmsot                                | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar       | None                                     |
       | UCH   | nonausea                             | 1.0                      | NoNausea-MC1.12-1.0.jar                       | None                                     |
       | UCH   | openmods                             | 0.12                     | OpenModsLib-1.12.2-0.12.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCH   | openblocks                           | 1.8                      | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCH   | thaumcraft                           | 6.1.BETA24               | Thaumcraft-1.12.2-6.1.BETA24.jar              | None                                     |
       | UCH   | ore_stone_variants                   | 4.0                      | ore_stone_variants-4.0.jar                    | None                                     |
       | UCH   | pamscookables                        | 1.1                      | pamscookables-1.1.jar                         | None                                     |
       | UCH   | parry                                | 1.0                      | parry-1.0-hotfix.jar                          | None                                     |
       | UCH   | passthroughsigns                     | 2.1.4                    | PassthroughSigns-1.12.2-2.1.4.jar             | None                                     |
       | UCH   | ping                                 | 1.4.4                    | Ping-1.12.2-1.4.4.jar                         | None                                     |
       | UCH   | pitweaks                             | 1.12-0.5.5               | PiTweaks-1.12-0.5.5.jar                       | None                                     |
       | UCH   | placebo                              | 1.4.1                    | Placebo-1.12.2-1.4.1.jar                      | None                                     |
       | UCH   | prettybeaches                        | 1.0.3                    | PrettyBeaches_1.12.2-1.0.3.jar                | None                                     |
       | UCH   | primitivemobs                        | 1.1.6                    | primitivemobs-1.1.6_beta.jar                  | None                                     |
       | UCH   | progressivebosses                    | 1.3.2                    | ProgressiveBosses-1.3.2-mc1.12.x.jar          | None                                     |
       | UCH   | quarkoddities                        | 1                        | QuarkOddities-1.12.2.jar                      | None                                     |
       | UCH   | quickleafdecay                       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
       | UCH   | randomtweaks                         | 1.12.2-2.1.5.0           | randomtweaks-1.12.2-2.1.5.0.jar               | None                                     |
       | UCH   | reap                                 | 1.5.2                    | reap-1.5.2.jar                                | None                                     |
       | UCH   | roughmobs                            | 2.0.0                    | roughmobs2-1.12.2_2.0.9.jar                   | None                                     |
       | UCH   | schematica                           | 1.8.0.169                | Schematica-1.12.2-1.8.0.169-universal.jar     | None                                     |
       | UCH   | sereneseasons                        | 1.2.6                    | SereneSeasons-1.12.2-1.2.6-universal.jar      | None                                     |
       | UCH   | serverobserver                       | 1.0.2.36                 | ServerObserver-1.12.2-1.0.2.36-universal.jar  | None                                     |
       | UCH   | servertabinfo                        | 1.2.2                    | ServerTabInfo-1.12.2-1.2.2.jar                | None                                     |
       | UCH   | solcarrot                            | 1.3.1                    | solcarrot-1.12.2-1.3.3.jar                    | None                                     |
       | UCH   | sophisticatedwolves                  | 3.13.4                   | SophisticatedWolves-1.12.2-3.13.4.jar         | None                                     |
       | UCH   | stackie                              | 1.6.0.48                 | Stackie-1.12.2-1.6.0.48-universal.jar         | None                                     |
       | UCH   | stg                                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                          | None                                     |
       | UCH   | supersoundmuffler                    | 1.0.2.9                  | supersoundmuffler-1.12.1-1.0.2.9.jar          | None                                     |
       | UCH   | surge                                | 2.0.72                   | Surge-1.12.2-2.0.72.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | tanspit                              | 1.12.2-1.3               | tanspit-1.12.2-1.3.jar                        | None                                     |
       | UCH   | thaumicperiphery                     | 0.2.4                    | thaumicperiphery-0.2.4.jar                    | None                                     |
       | UCH   | thutessentials                       | 2.2.16                   | thutessentials-1.12.2-2.2.16.jar              | None                                     |
       | UCH   | thutperms                            | 2.1.9@                   | thutpermissions-1.12.2-2.1.9.jar              | None                                     |
       | UCH   | tracer                               | 1.0.0.8                  | Tracer-1.12.2-1.0.0.8-universal.jar           | None                                     |
       | UCH   | trashslot                            | 8.4.6                    | TrashSlot_1.12.1-8.4.6.jar                    | None                                     |
       | UCH   | twitchcrumbs                         | 3.0.4                    | Twitchcrumbs_1.12.2-3.0.4.jar                 | None                                     |
       | UCH   | unloader                             | 1.2.0                    | unloader-1.2.0.jar                            | None                                     |
       | UCH   | vanillafix                           | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                       | None                                     |
       | UCH   | veinminer                            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
       | UCH   | veinminermodsupport                  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
       | UCH   | waim                                 | 1.0.0                    | WAIM-1.0.0.jar                                | None                                     |
       | UCH   | wawla                                | 2.5.261                  | Wawla-1.12.2-2.5.261.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | waystones                            | 4.0.63                   | Waystones_1.12.2-4.0.63.jar                   | None                                     |
       | UCH   | wgblockreplacer                      | 1.0.1                    | WGBlockReplacer-1.0.1.jar                     | None                                     |
       | UCH   | withercrumbs                         | @version@                | witherCrumbs-1.12.2-0.10.jar                  | None                                     |
       | UCH   | wolfarmor                            | 2.2.3.6                  | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |
       | UCH   | worleycaves                          | 1.3.0                    | worleycaves-1.3.0.jar                         | None                                     |
       | UCH   | xpfromharvest                        | 1.0                      | xpfromharvest-1.12-1.0.1.jar                  | None                                     |
       | UCH   | zombieawareness                      | 1.12.1-1.11.14           | zombieawareness-1.12.1-1.11.14.jar            | None                                     |
       | UCH   | passableleaves                       | 2.0.0                    | PassableLeaves-1.12.2-2.0.0.jar               | None                                     |
       | UCH   | totemexpansion                       | 1.2.2                    | totemexpansion-1.2.2-1.12.2.jar               | None                                     |
       | UCH   | hungeroverhaul                       | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar    | None                                     |
       | UCH   | justthetips                          | 1.12-1.0.1.1             | justthetips-1.12-1.0.1.1.jar                  | None                                     |
       | UCH   | peckish                              | 1.1.0                    | Peckish-1.12-1.1.0.jar                        | None                                     |
```

**Comment by T145** [comment]
Ran the server w/ only this mod installed and the same error occurred. Going into the config and removing all entries under "variant adder" let it load, but didn't generate any ores in the world.

**Comment by PersonTheCat** [comment]
Thanks. This is a super easy problem to fix. I'll have it out pretty soon and will let you know when.

**Comment by PersonTheCat** [comment]
Went ahead and fixed this and was able to verify that everything is working. The update will be out as soon as it gets approved. Please let me know if you have any other issues.

**Comment by T145** [comment]
I'm not seeing an uploaded release. Shouldn't be 9 hours before CF mods permit your release.

**Comment by PersonTheCat** [comment]
I know. I'm not sure what the problem is. It's outside of my control at the moment, though. In the meantime, here's a zip that contains 4.1. 
[ore_stone_variants-4.1.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2431093/ore_stone_variants-4.1.zip)
