### ISSUE TITLE
Server crash with world gen changes 2.4

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#7]
Version: 2.4

Biomes O Plenty world

Mods: https://www.modlister.com/user/pupnewfster

```
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at personthecat.mod.world.gen.WorldGenCustomOres.canRunGenerator(WorldGenCustomOres.java:199)
	at personthecat.mod.world.gen.WorldGenCustomOres.generate(WorldGenCustomOres.java:174)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

Edit: Upon restarting the server and changing thermal foundation support back to false (it had changed when the localization for config entry changed) I am unable to reproduce this,

**Comment by PersonTheCat** [comment]
I tested creating a new Biomes O' Plenty world in the newest version of Forge for 1.12.2, 2653, and did not experience any crashes. _However,_ I do see something on that line I forgot to change. And there's a good chance it was the same function. [This version](https://drive.google.com/open?id=18Zmayqx4iZz__lvHvf1TVFoECByyH-1q) uses a different function which does the same thing. If that doesn't fix it, I'm willing to somehow download those mods to see if I can figure out where the issue is. 

Thanks!

**Comment by pupnewfster** [comment]
The issue as my edit says is that I was unable to repeat it, but I decided to leave the issue open in case there was anything that you saw wrong on the line. So now that you have looked and changed whatever it was you noticed I am going to close this issue.
