### ISSUE TITLE
error

### ISSUE THREAD

**Issue by spb00000** [PersonTheCat/ore_stone_variants#92]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/28/20 5:38 PM
Description: Initializing game

java.lang.RuntimeException: There is no block named "modernmetals:stainlesssteel_ore."
	at com.personthecat.orestonevariants.util.CommonMethods.runExF(CommonMethods.java:83)
	at com.personthecat.orestonevariants.util.HjsonTools.noBlockNamed(HjsonTools.java:629)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$null$0(OreProperties.java:88)
	at java.util.Optional.orElseThrow(Unknown Source)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$new$1(OreProperties.java:88)
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35)
	at com.personthecat.orestonevariants.item.VariantItem.func_77653_i(VariantItem.java:65)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.personthecat.orestonevariants.util.CommonMethods.runExF(CommonMethods.java:83)
	at com.personthecat.orestonevariants.util.HjsonTools.noBlockNamed(HjsonTools.java:629)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$null$0(OreProperties.java:88)
	at java.util.Optional.orElseThrow(Unknown Source)
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$new$1(OreProperties.java:88)
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35)
	at com.personthecat.orestonevariants.item.VariantItem.func_77653_i(VariantItem.java:65)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976672792 bytes (931 MB) / 1974992896 bytes (1883 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -Xmx9216m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version      | Source                                  | Signature                                |
	|:----- |:---------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft              | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp                    | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML                    | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                  | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | mmdlib                 | 1.0.0-rc2    | MMDLib-1.12-1.0.0-rc2.36.jar            | None                                     |
	| LCH   | basemetals             | 2.5.0-rc2    | BaseMetals-1.12-2.5.0-rc2.332.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bookshelf              | 2.3.590      | Bookshelf-1.12.2-2.3.590.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | gbook                  | 2.9.5        | Guidebook-1.12.2-2.9.5.jar              | None                                     |
	| LCH   | waila                  | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar             | None                                     |
	| LCH   | jei                    | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar               | None                                     |
	| LCH   | jeresources            | 0.9.2.60     | JustEnoughResources-1.12.2-0.9.2.60.jar | None                                     |
	| LCH   | jeroreintegration      | 1.1.0        | JEROreIntegration-1.12.2-1.1.0.jar      | None                                     |
	| LCH   | modernmetals           | 2.5.0-rc2    | ModernMetals-1.12-2.5.0-rc2.152.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | orespawn               | 3.3.1        | OreSpawn-1.12-3.3.1.179.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | redstoneflux           | 2.1.1        | RedstoneFlux-1.12-2.1.1.1-universal.jar | None                                     |
	| LCH   | rockhounding_core      | 3.22         | rockhounding_core-1.12.2-3.22.jar       | None                                     |
	| LCH   | rockhounding_chemistry | 1.12.2-3.48  | rockhounding_chemistry-1.12.2-3.48.jar  | None                                     |
	| LCH   | rockhounding_oretiers  | 1.12.2-3.10  | rockhounding_oretiers-1.12.2-3.10.jar   | None                                     |
	| LCH   | mineralogy             | 3.8.0        | Mineralogy-1.12.2-3.8.0.53.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | osv                    | 5.3          | Ore Stone Variants-5.3-1.12.jar         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
```

maybe config problem?

**Comment by PersonTheCat** [comment]
This was resolved on Discord. Got anyone wondering, you just need to remove the blocks from the block list / property group. The preset will still get written to the disk, but this is intended functionality.

**Comment by spb00000** [comment]
@pupnewfster 
> This was resolved on Discord. Got anyone wondering, you just need to remove the blocks from the block list / property group. The preset will still get written to the disk, but this is intended functionality.

This method is not enough to solve this problem. You need to go to `config\osv\ores` and change `.hjson` file what is causing the problem. Change non-exist item to exist one, like `minecraft:dirt`. 

Here's an example of how to change `modernmetals_aluminumbrass_ore.hjson`

name: modernmetals_aluminumbrass_ore
```
mod: modernmetals
block: {
  location: **minecraft:dirt**
  hardness: 7.5
  level: 2
}
loot: [
  {
    item: **minecraft:dirt**
    count: [ 1, 1 ]
    xp: [ 0, 0 ]
    chance: 1
  }
]
texture: {
  shade: false
  original: modernmetals:blocks/aluminumbrass_ore
}

```
