### ISSUE TITLE
There are no properties named coal_ore crash

### ISSUE THREAD

**Issue by Bab095** [PersonTheCat/ore_stone_variants#96]
here is the report

Failure message: Ore Stone Variants (osv) encountered an error during the load_registries event phase
		java.lang.RuntimeException: There are no properties named "coal_ore." Fix your property group.
	Mod Version: null
	Exception message: java.lang.RuntimeException: There are no properties named "coal_ore." Fix your property group.
Stacktrace:
	at com.personthecat.orestonevariants.util.CommonMethods.runExF(CommonMethods.java:93) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$null$8(OreProperties.java:154) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.OreProperties$$Lambda$3548/1037220289.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at com.personthecat.orestonevariants.properties.OreProperties.lambda$of$9(OreProperties.java:154) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.OreProperties$$Lambda$3546/1013700132.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at com.personthecat.orestonevariants.properties.OreProperties.of(OreProperties.java:155) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup.lambda$setupPropertyGroups$0(PropertyGroup.java:44) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup$$Lambda$3543/41975027.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at com.personthecat.orestonevariants.properties.PropertyGroup.setupPropertyGroups(PropertyGroup.java:42) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.Main$$Lambda$3082/1133161119.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.SafeRegistry.lambda$new$0(SafeRegistry.java:17) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry$$Lambda$3077/614159535.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry.iterator(SafeRegistry.java:42) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.CommonMethods.find(CommonMethods.java:132) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup.getDefaultProperties(PropertyGroup.java:83) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup$$Lambda$3541/1412428103.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup.getHardCoded(PropertyGroup.java:68) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.properties.PropertyGroup.findOrCreate(PropertyGroup.java:59) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.blocks.BlockEntry.<init>(BlockEntry.java:21) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.blocks.BlockEntry.create(BlockEntry.java:29) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.blocks.BlockEntry$$Lambda$3538/742343633.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at com.personthecat.orestonevariants.blocks.BlockEntry.setupEntries(BlockEntry.java:39) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.Main$$Lambda$3083/1209981276.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.SafeRegistry.lambda$new$0(SafeRegistry.java:17) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry$$Lambda$3077/614159535.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry.iterator(SafeRegistry.java:42) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.init.BlockInit.setupBlocks(BlockInit.java:15) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.Main$$Lambda$3078/447482439.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.SafeRegistry.lambda$new$0(SafeRegistry.java:17) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry$$Lambda$3077/614159535.get(Unknown Source) ~[?:?] {}
	at com.personthecat.orestonevariants.util.Lazy.get(Lazy.java:35) ~[?:5.6] {re:classloading}
	at com.personthecat.orestonevariants.util.SafeRegistry.iterator(SafeRegistry.java:42) ~[?:5.6] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_51] {}
	at com.personthecat.orestonevariants.init.RegistryHandler.registerBlocks(RegistryHandler.java:31) ~[?:5.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_161_RegistryHandler_registerBlocks_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$null$4(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3137/1092179900.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.registries.GameData.lambda$null$13(GameData.java:359) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$$Lambda$3533/22958662.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3134/993062597.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2916/1386640019.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2917/2034036629.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.0.7.jar:34.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/619621481.call(Unknown Source) [forge-1.16.3-34.0.7.jar:34.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

**Comment by PersonTheCat** [comment]
Hello. This message just means that you have either deleted coal_ore.hjson, replaced the value `name` inside of it, or disabled vanilla support in the config file without removing coal ore from the block list. Can you confirm that none of these have happened? If so, please share your config file and I will try it.

**Comment by TheCrazy69** [comment]
> Hello. This message just means that you have either deleted coal_ore.json, replaced the value `name` inside of it, or disabled vanilla support in the config file without removing coal ore from the block list. Can you confirm that none of these have happened? If so, please share your config file and I will try it.

the same happens to me, I haven't changed anything and it throws that error, both when downloading from the curse forge page and the launcher mod menu.
I would send you the config file you told to send, but I can't seem to find it. could you please tell me where in the .jar file it is?

**Comment by bessiq** [comment]
Just discovered this mod and wanted to try it out on 1.16.3, but ran into the same issue. I tested it with no other mods on Forge 34.1.18, using the default config for OSV.

The good news is, I think I've found cause of the issue. It seems that `osv-common.hjson` is being read before the `config/osv` folder is generated (which has the default ore files, such as `coal_ore.hjson`). Removing all of the default entries in `propertyGroups` allows the game to load and the `osv` folder to generate. Then you can re-add those entries and it appears to be working (for instance, I have found andesite coal ore).

Anyway, it should hopefully be an easy fix, and this workaround does the trick for now. 🙂

**Comment by PersonTheCat** [comment]
Hello. Sorry this took me so long to get back to! I've been practicing web development lately for my new job and just really need to devote my attention to that for a while. I believe I have fixed this bug now. Please unzip and try out the new version below, if you have the chance. 

Thanks again! 
[Ore Stone Variants-5.7-1.16.3.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5373069/Ore.Stone.Variants-5.7-1.16.3.zip)

**Comment by bessiq** [comment]
No worries. I downloaded and tested the new version and it seems to be working fine - no errors, and I found some diorite coal ore right away.

Thanks for the quick update. Now I just gotta wrap my head around these configs... 😅 

Good luck on the new gig!

**Comment by PersonTheCat** [comment]
@bessiq Thank you! Stop by [the Discord server](https://discord.gg/9vhahAE) if you need help.
