### ISSUE TITLE
Newer Forge Versions Crash

### ISSUE THREAD

**Issue by WenXin20** [PersonTheCat/ore_stone_variants#99]
`Minecraft v1.16.3`
`Forge v34.1.33`
`Ore Stone Variants v5.7`

Newer Forge versions are crashing due to a Forge change:
<details>
  <summary>Error Log (Click Here)</summary>
  
  ```
[09:26:29] [Render thread/ERROR]: Exception caught during firing event: Can not register to a locked registry. Modder should use Forge Register methods.
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerOreFeatures(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerOrePlacement(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56)
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72)
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40)
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456)
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452)
	at com.personthecat.orestonevariants.init.RegistryHandler.registerOrePlacement(RegistryHandler.java:49)
	at net.minecraftforge.eventbus.ASMEventHandler_593_RegistryHandler_registerOrePlacement_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111)
	at net.minecraftforge.fml.ModContainer$$Lambda$3401/494865616.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2939/1226973575.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2940/1581377197.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/405587614.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[09:26:29] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:worldgen/decorator> dispatch for modid osv
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
	at com.personthecat.orestonevariants.init.RegistryHandler.registerOrePlacement(RegistryHandler.java:49) ~[?:5.7]
	at net.minecraftforge.eventbus.ASMEventHandler_593_RegistryHandler_registerOrePlacement_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:34.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3401/494865616.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) [?:?]
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) [?:?]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2939/1226973575.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2940/1581377197.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.33.jar:34.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/405587614.call(Unknown Source) [forge-1.16.3-34.1.33.jar:34.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?]
[09:26:29] [Render thread/INFO]: Registering Features
  ```
  
</details>

**Comment by Nahkranoth0** [comment]
Also, happening to me

Forge version: 34.1.42
Mod Version : 5.7-16.2.jar

Description: Upon opening minecraft and loading the mod itself it outputs the following error:
"Exception caught during firing event: Can not register to a locked registry. Modder should use Forge Register methods."

Even with a modpack with just this specific mod, it won't work at all.

Pastebin: https://pastebin.com/wL1Q6qU1 latest.log
https://pastebin.com/4GyAQB62 crash.log

**Comment by PersonTheCat** [comment]
This has been fixed in the latest version.
